# Generated by Django 4.1.7 on 2023-06-12 16:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Credit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=100, verbose_name='Название банка')),
                ('amount', models.IntegerField(verbose_name='Сумма задолженности')),
                ('credit_term', models.IntegerField(verbose_name='Срок задолженности')),
                ('debt_percent', models.IntegerField(verbose_name='Процент задолженности')),
            ],
        ),
    ]
